--------------------step 1 DB EXPLORATION---------

-- Explore all objects in the DB
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore columns from the DB
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

----------Step 2 Dimensions Exploration-----------
/* Identifying the unq values in each dimension. Used for recognizing how data might be grouped or segmented later for analysis.
*/

-- Explore all countries our customers come from.
SELECT DISTINCT country
FROM gold.dim_customers;

-- explore all categories 'The major divisions'

SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1, 2, 3;

-------------STEP 3 Date Exploration----------------
-- Identify the earliest and latest dates. Understand the scope of data and time span
-- Using MIN/MAX of dates for exploration
-- Identify the earliest and latest dates. Boundaries

SELECT
    MIN(order_date) AS first_order,
    MAX(order_date) AS last_order,
    DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years,
    DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales;

-- Finding the youngest and eldest customer

SELECT
    MIN(birthdate) AS oldest_cust,
    DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_cust,
    DATEDIFF(year, MAX(birthdate), GETDATE()) AS younges_age
FROM gold.dim_customers

--Step 4 : Measures exploration
-- Calculate the key metric of the business. Highest level of aggregation and lowest level of details.
 
 -- Finding the total sales.
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales;

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales;

-- Find the average selling price
SELECT AVG(price) AS avg_price
FROM gold.fact_sales;

-- FInd the total number of orders
SELECT COUNT(DISTINCT order_number) AS total_sales
FROM gold.fact_sales;

-- Find the total number of products
SELECT COUNT(DISTINCT product_key) AS total_producs
FROM gold.dim_products;

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers;

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales;

-- Now combine all the above values and combine them as a report. 
-- Generate a report that shows all the key metrics of the business.

SELECT 'Total Sales' AS Measure_name, SUM(sales_amount) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total quantity' AS Measure_name, SUM(quantity) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS Measure_name, AVG(price) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total orders' AS Measure_name, COUNT(DISTINCT order_number) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total products' AS Measure_name, COUNT(product_key) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total customers' AS Measure_name, COUNT(customer_key) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total order placed customers' AS Measure_name, COUNT(DISTINCT customer_key) AS Measure_value FROM gold.fact_sales;

-- Step 5: Magnitude Analysis.------------
-- Compare the measure values by categories. It helps us to understand the importance of different categories.
-- Aggregating the measures by dimensions.

-- Find the total customers by countries
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total
FROM gold.dim_customers
GROUP BY gender
ORDER BY total DESC;

-- Find the total products by category
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category
SELECT
    category,
    AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the total revenye generated for each category
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

 ---------Ranking Analysis-------------
 -- Order the values of dimensions by measure
 -- Top N and bottom N performers.

 -- Which 5 products generate the highest revenue

SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- What are the 5 worst performing products
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue;

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_sales
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS s
    ON c.customer_key = s.customer_key
GROUP BY
        c.customer_key,
        c.first_name,
        c.last_name
ORDER BY total_sales DESC;

-- Find the 3 customers with fewest orders placed.
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT s.order_number) AS total_orders
FROM gold.dim_customers AS c
LEFT JOIN gold.fact_sales AS s
    ON c.customer_key = s.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders ASC;
